# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\RegUser:
            algorithm: bcrypt

    encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt


    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
                    memory:
                        users:
                            user:
                                password: 123456
                                roles: 'ROLE_USER'
                            admin:
                                password: admin
                                roles: 'ROLE_ADMIN'
        our_db_provider:
            entity:
                class: AppBundle:RegUser



    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            http_basic: ~
#            provider: psql
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                check_path: login_check
                login_path: login

                always_use_default_target_path: false
                default_target_path:  /messenger/index.html
                always_use_default_target_path: true
                target_path_parameter:  _target_path
                use_referer:  true

                failure_path:    /login
                failure_forward: false
                failure_path_parameter: _failure_path
#                failure_handler: some.service.id
#                success_handler: some.service.id

                username_parameter: _username
                password_parameter: _password

                post_only:      true
                remember_me:    false

#                provider: fos_userbundle
#                csrf_provider: security.csrf.token_manager

#            remember_me:
#                token_provider: name
#                secret: "%secret%"
#                name: NameOfTheCookie
#                lifetime: 3600 # in seconds
#                path: /messenger/index
#                domain: somedomain.foo
#                secure: false
#                httponly: true
#                always_remember_me: false
#                remember_me_parameter: _remember_me
            logout:
                path:   /logout
                target: /
                invalidate_session: false
                delete_cookies:
                    a: { path: null, domain: null }
                    b: { path: null, domain: null }
#                handlers: [some.service.id, another.service.id]
#                success_handler: some.service.id
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: ROLE_ADMIN }